spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: get_route
        uri: http://192.168.8.112:8083
#        uri: http://spring.io/
        predicates:
        - Path=/shopapi/**/**


server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug