spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#      - id: shop_route
#        uri: http://192.168.8.112:8083
##        uri: http://spring.io/
#        predicates:
#        - Path=/shopapi/**
      - id: goods_route
        uri: http://192.168.8.112:8084
        predicates:
        - Path=/goods/**

server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
logging:
  level:
    org.springframework.cloud.gateway: info
    org.springframework.jdbc.core.JdbcTemplate: debug