spring:
  aop:
    proxy-target-class: true
    auto: true
  application:
    name: shop-service-provider
  datasource:
    druid:
      write:
        url: jdbc:mysql://192.168.8.112:3306/yun_shop?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      read:
        url: jdbc:mysql://192.168.8.112:3306/yun_shop_slave1?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      sharding:
        url: jdbc:mysql://192.168.8.112:8066/TESTDB?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    min-idle: 5
    max-active: 20
    initial-size: 5
    max-wait: 10000
    default-auto-commit: true


server:
  port: 8085
management:
  endpoint:
    mappings:
      enabled: true
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  httpclient:
    enabled: true
